# Generated by Django 6.0.3 on 2026-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('alarm_type', models.CharField(choices=[('temp_high', '温度偏高'), ('temp_low', '温度偏低'), ('humidity_high', '湿度偏高'), ('humidity_low', '湿度偏低')], max_length=20, verbose_name='报警类型')),
                ('alarm_value', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='报警值')),
                ('threshold', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='阈值')),
                ('alarm_time', models.DateTimeField(verbose_name='报警时间')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
            ],
            options={
                'verbose_name': '环境报警',
                'verbose_name_plural': '环境报警',
                'ordering': ['-alarm_time'],
            },
        ),
        migrations.CreateModel(
            name='EnvRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='温度(°C)')),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='湿度(%)')),
                ('recorded_at', models.DateTimeField(verbose_name='记录时间')),
                ('is_alarm', models.BooleanField(default=False, verbose_name='是否报警')),
            ],
            options={
                'verbose_name': '环境记录',
                'verbose_name_plural': '环境记录',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='监控点位名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='点位编码')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置描述')),
                ('temp_min', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='温度下限(°C)')),
                ('temp_max', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='温度上限(°C)')),
                ('humidity_min', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='湿度下限(%)')),
                ('humidity_max', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='湿度上限(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '监控点位',
                'verbose_name_plural': '监控点位',
                'ordering': ['code'],
            },
        ),
    ]
