# Generated by Django 6.0.3 on 2026-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('finding_type', models.CharField(choices=[('nonconformity', '不符合项'), ('observation', '观察项'), ('improvement', '改进建议')], max_length=20, verbose_name='发现类型')),
                ('clause', models.CharField(blank=True, max_length=100, verbose_name='涉及条款')),
                ('description', models.TextField(verbose_name='描述')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='责任部门')),
            ],
            options={
                'verbose_name': '审核发现',
                'verbose_name_plural': '审核发现',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('complaint_no', models.CharField(max_length=50, unique=True, verbose_name='投诉编号')),
                ('complainant', models.CharField(max_length=100, verbose_name='投诉人')),
                ('complaint_date', models.DateField(verbose_name='投诉日期')),
                ('content', models.TextField(verbose_name='投诉内容')),
                ('investigation', models.TextField(blank=True, verbose_name='调查结果')),
                ('handling_result', models.TextField(blank=True, verbose_name='处理意见')),
                ('status', models.CharField(choices=[('received', '已接收'), ('investigating', '调查中'), ('resolved', '已处理'), ('closed', '已关闭')], default='received', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '投诉',
                'verbose_name_plural': '投诉',
                'ordering': ['-complaint_date'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('root_cause', models.TextField(verbose_name='原因分析')),
                ('action_plan', models.TextField(verbose_name='纠正措施')),
                ('deadline', models.DateField(verbose_name='完成期限')),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('verified', '已验证')], default='open', max_length=20, verbose_name='状态')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('verification_result', models.TextField(blank=True, verbose_name='验证结果')),
            ],
            options={
                'verbose_name': '纠正措施',
                'verbose_name_plural': '纠正措施',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('audit_no', models.CharField(max_length=50, unique=True, verbose_name='审核编号')),
                ('title', models.CharField(max_length=200, verbose_name='审核主题')),
                ('audit_type', models.CharField(choices=[('scheduled', '例行审核'), ('special', '专项审核')], max_length=20, verbose_name='审核类型')),
                ('scope', models.TextField(verbose_name='审核范围')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际日期')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('in_progress', '进行中'), ('completed', '已完成'), ('closed', '已关闭')], default='planned', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '内部审核',
                'verbose_name_plural': '内部审核',
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='ManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('review_no', models.CharField(max_length=50, unique=True, verbose_name='评审编号')),
                ('title', models.CharField(max_length=200, verbose_name='评审主题')),
                ('review_date', models.DateField(verbose_name='评审日期')),
                ('participants', models.TextField(blank=True, verbose_name='参会人员')),
                ('input_materials', models.TextField(blank=True, verbose_name='输入材料')),
                ('minutes', models.TextField(blank=True, verbose_name='会议纪要')),
                ('status', models.CharField(choices=[('planned', '计划中'), ('completed', '已完成'), ('closed', '已关闭')], default='planned', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '管理评审',
                'verbose_name_plural': '管理评审',
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('nc_no', models.CharField(max_length=50, unique=True, verbose_name='不符合项编号')),
                ('source', models.CharField(choices=[('internal', '内部发现'), ('audit', '审核发现'), ('complaint', '投诉'), ('proficiency', '能力验证'), ('other', '其他')], max_length=20, verbose_name='来源')),
                ('description', models.TextField(verbose_name='描述')),
                ('impact_assessment', models.TextField(blank=True, verbose_name='影响评价')),
                ('corrective_action', models.TextField(blank=True, verbose_name='纠正措施')),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '进行中'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='关闭日期')),
            ],
            options={
                'verbose_name': '不符合项',
                'verbose_name_plural': '不符合项',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProficiencyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('organizer', models.CharField(max_length=200, verbose_name='组织单位')),
                ('test_item', models.CharField(max_length=200, verbose_name='检测项目')),
                ('participation_date', models.DateField(verbose_name='参加日期')),
                ('result', models.CharField(choices=[('satisfactory', '满意'), ('questionable', '有问题'), ('unsatisfactory', '不满意'), ('pending', '待评')], default='pending', max_length=20, verbose_name='结果')),
                ('report', models.TextField(blank=True, verbose_name='报告')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='proficiency/', verbose_name='附件')),
            ],
            options={
                'verbose_name': '能力验证',
                'verbose_name_plural': '能力验证',
                'ordering': ['-participation_date'],
            },
        ),
        migrations.CreateModel(
            name='QualitySupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('plan_no', models.CharField(max_length=50, unique=True, verbose_name='监督计划编号')),
                ('supervision_date', models.DateField(verbose_name='监督日期')),
                ('scope', models.TextField(verbose_name='监督范围')),
                ('findings', models.TextField(blank=True, verbose_name='发现')),
                ('conclusion', models.CharField(choices=[('conforming', '符合'), ('nonconforming', '不符合')], max_length=20, verbose_name='结论')),
            ],
            options={
                'verbose_name': '质量监督',
                'verbose_name_plural': '质量监督',
                'ordering': ['-supervision_date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('content', models.TextField(verbose_name='决议内容')),
                ('deadline', models.DateField(verbose_name='完成期限')),
                ('status', models.CharField(choices=[('open', '待处理'), ('completed', '已完成')], default='open', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '评审决议',
                'verbose_name_plural': '评审决议',
                'ordering': ['-created_at'],
            },
        ),
    ]
