# Generated by Django 6.0.3 on 2026-03-31 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_initial'),
        ('standards', '0004_standard_no_partial_unique'),
        ('testing', '0002_recordtemplate_test_parameter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='资质配置名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='生效日期（可选）')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='失效日期（可选）')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='qualification/', verbose_name='资质附件')),
                ('allowed_record_templates', models.ManyToManyField(blank=True, related_name='qualification_profiles', to='testing.recordtemplate', verbose_name='允许使用的原始记录模板')),
                ('allowed_standards', models.ManyToManyField(blank=True, related_name='qualification_profiles', to='standards.standard', verbose_name='允许使用的标准规范')),
                ('allowed_test_methods', models.ManyToManyField(blank=True, related_name='qualification_profiles', to='testing.testmethod', verbose_name='允许使用的检测方法')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '资质配置',
                'verbose_name_plural': '资质配置',
                'ordering': ['-created_at'],
            },
        ),
    ]
