# Generated by Django 6.0.3 on 2026-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_qualificationprofile'),
        ('testing', '0005_recordtemplate_test_parameters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualificationprofile',
            name='allowed_test_methods',
        ),
        migrations.AddField(
            model_name='qualificationprofile',
            name='allowed_parameters',
            field=models.ManyToManyField(blank=True, related_name='qualification_profiles', to='testing.testparameter', verbose_name='允许使用的检测参数'),
        ),
    ]
