# Generated by Django 5.2.12 on 2026-03-31 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_qualificationprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfinding',
            name='evidence',
            field=models.TextField(blank=True, verbose_name='证据/依据'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='责任人'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='severity',
            field=models.CharField(choices=[('major', '严重'), ('minor', '一般'), ('low', '轻微')], default='minor', max_length=20, verbose_name='严重程度'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='status',
            field=models.CharField(choices=[('open', '待处理'), ('action_planned', '措施已制定'), ('action_completed', '措施已完成'), ('verified', '已验证有效'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='completion_evidence',
            field=models.TextField(blank=True, verbose_name='完成证据'),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='verification_date',
            field=models.DateField(blank=True, null=True, verbose_name='验证日期'),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_actions', to=settings.AUTH_USER_MODEL, verbose_name='验证人'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='auditors',
            field=models.ManyToManyField(blank=True, related_name='participated_audits', to=settings.AUTH_USER_MODEL, verbose_name='审核员'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='conclusion',
            field=models.TextField(blank=True, verbose_name='审核结论'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='improvement_count',
            field=models.IntegerField(default=0, verbose_name='改进建议数'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='nonconformity_count',
            field=models.IntegerField(default=0, verbose_name='不符合项数'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='observation_count',
            field=models.IntegerField(default=0, verbose_name='观察项数'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='quality/audit_reports/', verbose_name='审核报告'),
        ),
        migrations.AddField(
            model_name='internalaudit',
            name='total_findings',
            field=models.IntegerField(default=0, verbose_name='发现项总数'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='status',
            field=models.CharField(choices=[('open', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('verified', '已验证'), ('rejected', '验证未通过')], default='open', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='internalaudit',
            name='audit_type',
            field=models.CharField(choices=[('scheduled', '例行审核'), ('special', '专项审核'), ('follow_up', '跟踪审核')], max_length=20, verbose_name='审核类型'),
        ),
    ]
