# Generated by Django 6.0.3 on 2026-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='耗材名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='耗材编码')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('unit', models.CharField(max_length=20, verbose_name='计量单位')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='分类')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='生产厂家')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='库存数量')),
                ('safety_stock', models.IntegerField(default=10, verbose_name='安全库存')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('storage_location', models.CharField(blank=True, max_length=200, verbose_name='存放位置')),
            ],
            options={
                'verbose_name': '耗材',
                'verbose_name_plural': '耗材',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('quantity', models.IntegerField(verbose_name='入库数量')),
                ('batch_no', models.CharField(max_length=100, verbose_name='批次号')),
                ('purchase_date', models.DateField(verbose_name='采购日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
            ],
            options={
                'verbose_name': '入库记录',
                'verbose_name_plural': '入库记录',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('quantity', models.IntegerField(verbose_name='出库数量')),
                ('purpose', models.CharField(max_length=200, verbose_name='用途')),
                ('out_date', models.DateField(verbose_name='出库日期')),
            ],
            options={
                'verbose_name': '出库记录',
                'verbose_name_plural': '出库记录',
                'ordering': ['-out_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='供应商名称')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='地址')),
                ('evaluation_score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='评价得分')),
                ('is_qualified', models.BooleanField(default=True, verbose_name='是否合格')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['name'],
            },
        ),
    ]
