# Generated by Django 6.0.3 on 2026-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('contract_no', models.CharField(max_length=100, unique=True, verbose_name='合同编号')),
                ('title', models.CharField(max_length=200, verbose_name='合同名称')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='合同金额')),
                ('sign_date', models.DateField(blank=True, null=True, verbose_name='签订日期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('scope', models.TextField(blank=True, verbose_name='检测范围')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='合同附件')),
            ],
            options={
                'verbose_name': '合同',
                'verbose_name_plural': '合同',
                'ordering': ['-sign_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='单位名称')),
                ('role', models.CharField(choices=[('builder', '建设单位'), ('contractor', '施工单位'), ('supervisor', '监理单位'), ('designer', '设计单位'), ('inspector', '检测单位')], max_length=20, verbose_name='单位角色')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '参建单位',
                'verbose_name_plural': '参建单位',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='工程名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='项目编号')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='工程地点')),
                ('project_type', models.CharField(choices=[('building', '房建工程'), ('municipal', '市政工程'), ('transport', '交通工程'), ('water', '水利工程'), ('airport', '机场工程'), ('other', '其他')], max_length=20, verbose_name='工程类型')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已竣工'), ('suspended', '已暂停')], default='active', max_length=20, verbose_name='项目状态')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开工日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='计划竣工日期')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工程项目',
                'verbose_name_plural': '工程项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='分部分项工程名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='编号')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '分部分项工程',
                'verbose_name_plural': '分部分项工程',
                'ordering': ['code', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='见证人姓名')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='证件号')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('certificate_no', models.CharField(blank=True, max_length=100, verbose_name='见证员证书号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在岗')),
            ],
            options={
                'verbose_name': '见证人',
                'verbose_name_plural': '见证人',
                'ordering': ['-created_at'],
            },
        ),
    ]
