#!/bin/bash

# Superpowers Helper Script for Qwen
# This script helps implement Superpowers methodology in Qwen

echo "==========================================="
echo "Welcome to Superpowers for Qwen!"
echo "==========================================="

echo ""
echo "Superpowers methodology includes:"
echo "1. Brainstorming - Refining ideas through questions"
echo "2. Planning - Breaking work into bite-sized tasks"
echo "3. Test-Driven Development - RED-GREEN-REFACTOR cycle"
echo "4. Systematic Debugging - Root cause analysis"
echo "5. Code Review - Quality assurance"
echo ""

echo "To use Superpowers with Qwen, follow these steps:"
echo ""
echo "1. When starting a new task, begin by brainstorming:"
echo "   - Describe your idea in detail"
echo "   - Ask clarifying questions"
echo "   - Define acceptance criteria"
echo ""
echo "2. Create a plan before implementing:"
echo "   - Break the task into small, specific steps"
echo "   - Define verification steps for each task"
echo "   - Specify exact file paths and changes"
echo ""
echo "3. Follow Test-Driven Development:"
echo "   - Write a failing test first"
echo "   - Implement minimal code to pass the test"
echo "   - Refactor while keeping tests passing"
echo ""
echo "4. Use systematic debugging when issues arise:"
echo "   - Reproduce the problem consistently"
echo "   - Isolate the root cause"
echo "   - Verify the fix resolves the issue"
echo ""
echo "5. Request code reviews:"
echo "   - Ask for feedback on your implementation"
echo "   - Address all critical and high-severity issues"
echo ""
echo "Ready to start using Superpowers? Just describe your task!"