# Generated by Django 6.0.3 on 2026-03-31 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_seed_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('notification_type', models.CharField(choices=[('commission_review', '委托待评审'), ('equipment_expiring', '设备即将到检'), ('sample_overdue', '样品超期'), ('task_assigned', '任务已分配'), ('record_review', '记录待复核'), ('report_audit', '报告待审核'), ('report_approve', '报告待批准'), ('quality_audit', '质量审核'), ('system', '系统通知')], max_length=50, verbose_name='类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('link_path', models.CharField(blank=True, max_length=200, verbose_name='跳转路径')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
