# Generated by Django 5.2.12 on 2026-03-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='证书有效期'),
        ),
        migrations.AddField(
            model_name='user',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='资质证书编号'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='电子签名'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签名更新时间'),
        ),
    ]
