# Generated by Django 6.0.3 on 2026-03-31 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=500, verbose_name='请求路径')),
                ('request_hash', models.CharField(max_length=64, verbose_name='请求摘要')),
                ('state', models.CharField(choices=[('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='processing', max_length=20, verbose_name='状态')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('response_body', models.TextField(blank=True, verbose_name='响应体')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='响应类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '幂等请求记录',
                'verbose_name_plural': '幂等请求记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128, verbose_name='幂等键'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='is_idempotent_replay',
            field=models.BooleanField(default=False, verbose_name='是否重放返回'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['idempotency_key'], name='idx_auditlog_idemp'),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to=settings.AUTH_USER_MODEL, verbose_name='请求用户'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['key'], name='idx_idemp_key'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['state'], name='idx_idemp_state'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['-created_at'], name='idx_idemp_created'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('user', 'key', 'method', 'path'), name='uniq_idemp_user_key_method_path'),
        ),
    ]
