# Generated by Django 6.0.3 on 2026-03-25 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0001_initial'),
        ('equipment', '0001_initial'),
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('template_version', models.CharField(max_length=20, verbose_name='使用模板版本')),
                ('record_data', models.JSONField(default=dict, verbose_name='记录数据')),
                ('env_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='环境温度(°C)')),
                ('env_humidity', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='环境湿度(%)')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待复核'), ('reviewed', '已复核'), ('returned', '已退回')], default='draft', max_length=20, verbose_name='状态')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='复核日期')),
                ('review_comment', models.TextField(blank=True, verbose_name='复核意见')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('recorder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_records', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
            options={
                'verbose_name': '原始记录',
                'verbose_name_plural': '原始记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(max_length=200, verbose_name='修改字段路径')),
                ('old_value', models.TextField(blank=True, verbose_name='原值')),
                ('new_value', models.TextField(blank=True, verbose_name='新值')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='testing.originalrecord', verbose_name='原始记录')),
            ],
            options={
                'verbose_name': '记录修改痕迹',
                'verbose_name_plural': '记录修改痕迹',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模板编号')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('schema', models.JSONField(verbose_name='表单定义')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '记录模板',
                'verbose_name_plural': '记录模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='originalrecord',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testing.recordtemplate', verbose_name='记录模板'),
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='检测类别')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='类别代码')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='testing.testcategory', verbose_name='上级类别')),
            ],
            options={
                'verbose_name': '检测类别',
                'verbose_name_plural': '检测类别',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='检测方法名称')),
                ('standard_no', models.CharField(max_length=100, verbose_name='标准号')),
                ('standard_name', models.CharField(max_length=300, verbose_name='标准名称')),
                ('description', models.TextField(blank=True, verbose_name='方法描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='testing.testcategory', verbose_name='检测类别')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '检测方法',
                'verbose_name_plural': '检测方法',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='recordtemplate',
            name='test_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='testing.testmethod', verbose_name='检测方法'),
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='参数名称')),
                ('code', models.CharField(max_length=50, verbose_name='参数代码')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('precision', models.IntegerField(default=1, verbose_name='修约精度(小数位数)')),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='最小值')),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='最大值')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='testing.testmethod', verbose_name='检测方法')),
            ],
            options={
                'verbose_name': '检测参数',
                'verbose_name_plural': '检测参数',
                'ordering': ['method', 'code'],
                'unique_together': {('method', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JudgmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('grade', models.CharField(max_length=100, verbose_name='强度等级/技术要求')),
                ('min_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='下限值')),
                ('max_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='上限值')),
                ('standard_ref', models.CharField(blank=True, max_length=200, verbose_name='标准依据')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('test_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='testing.testparameter', verbose_name='检测参数')),
            ],
            options={
                'verbose_name': '判定规则',
                'verbose_name_plural': '判定规则',
                'ordering': ['test_parameter', 'grade'],
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('task_no', models.CharField(max_length=50, unique=True, verbose_name='任务编号')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='计划检测日期')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='实际检测日期')),
                ('status', models.CharField(choices=[('unassigned', '待分配'), ('assigned', '待检'), ('in_progress', '检测中'), ('completed', '已完成'), ('abnormal', '异常')], default='unassigned', max_length=20, verbose_name='状态')),
                ('age_days', models.IntegerField(blank=True, null=True, verbose_name='龄期(天)')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('assigned_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipment', verbose_name='使用设备')),
                ('assigned_tester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='检测员')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='commissions.commission', verbose_name='委托单')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='samples.sample', verbose_name='样品')),
                ('test_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testmethod', verbose_name='检测方法')),
                ('test_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.testparameter', verbose_name='检测参数')),
            ],
            options={
                'verbose_name': '检测任务',
                'verbose_name_plural': '检测任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('raw_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='原始值')),
                ('rounded_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='修约后值')),
                ('display_value', models.CharField(blank=True, max_length=100, verbose_name='显示值')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('judgment', models.CharField(choices=[('qualified', '合格'), ('unqualified', '不合格'), ('na', '不判定')], default='na', max_length=20, verbose_name='判定结论')),
                ('standard_value', models.CharField(blank=True, max_length=100, verbose_name='标准限值')),
                ('design_value', models.CharField(blank=True, max_length=100, verbose_name='设计值')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testparameter', verbose_name='检测参数')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testing.testtask', verbose_name='检测任务')),
            ],
            options={
                'verbose_name': '检测结果',
                'verbose_name_plural': '检测结果',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='originalrecord',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='testing.testtask', verbose_name='检测任务'),
        ),
        migrations.AddIndex(
            model_name='testtask',
            index=models.Index(fields=['status'], name='idx_task_status'),
        ),
        migrations.AddIndex(
            model_name='testtask',
            index=models.Index(fields=['planned_date'], name='idx_task_planned_date'),
        ),
        migrations.AddIndex(
            model_name='testtask',
            index=models.Index(fields=['assigned_tester'], name='idx_task_tester'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['task', 'parameter'], name='idx_result_task_param'),
        ),
        migrations.AddIndex(
            model_name='originalrecord',
            index=models.Index(fields=['status'], name='idx_record_status'),
        ),
    ]
