# Generated by Django 5.2.12 on 2026-03-31 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_recordtemplate_test_parameter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='originalrecord',
            name='data_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='数据哈希'),
        ),
        migrations.AddField(
            model_name='originalrecord',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='是否锁定'),
        ),
        migrations.AddField(
            model_name='recordrevision',
            name='comment',
            field=models.TextField(blank=True, verbose_name='修改备注'),
        ),
        migrations.AlterField(
            model_name='recordrevision',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='recordrevision',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddIndex(
            model_name='recordrevision',
            index=models.Index(fields=['record', '-changed_at'], name='idx_revision_record_time'),
        ),
    ]
