# Generated by Django 6.0.3 on 2026-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_task_status_remove_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='status',
            field=models.CharField(choices=[('unassigned', '待分配'), ('in_progress', '检测中'), ('completed', '已完成'), ('abnormal', '异常')], default='unassigned', max_length=20, verbose_name='状态'),
        ),
    ]
