# Generated by Django 6.0.3 on 2026-04-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_alter_testtask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtemplate',
            name='test_parameters',
            field=models.ManyToManyField(blank=True, related_name='record_templates_multi', to='testing.testparameter', verbose_name='关联检测参数'),
        ),
        migrations.AddField(
            model_name='recordtemplate',
            name='word_template',
            field=models.FileField(blank=True, null=True, upload_to='record_templates/', verbose_name='Word模板'),
        ),
    ]
