# Generated by Django 6.0.3 on 2026-04-01 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0004_standard_no_partial_unique'),
        ('testing', '0005_recordtemplate_test_parameters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testparameter',
            options={'ordering': ['category', 'code'], 'verbose_name': '检测参数', 'verbose_name_plural': '检测参数'},
        ),
        migrations.AlterUniqueTogether(
            name='testparameter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='recordtemplate',
            name='test_method',
        ),
        migrations.AddField(
            model_name='testparameter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameters', to='testing.testcategory', verbose_name='检测类别'),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='description',
            field=models.TextField(blank=True, verbose_name='说明'),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameters', to='standards.standard', verbose_name='依据标准'),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='standard_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='标准名称'),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='standard_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='标准号'),
        ),
        migrations.AlterField(
            model_name='testparameter',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='testing.testmethod', verbose_name='检测方法(旧)'),
        ),
    ]
