# Generated by Django 6.0.3 on 2026-04-01

from django.db import migrations


def forwards(apps, schema_editor):
    TestMethod = apps.get_model('testing', 'TestMethod')
    TestParameter = apps.get_model('testing', 'TestParameter')
    TestTask = apps.get_model('testing', 'TestTask')
    Standard = apps.get_model('standards', 'Standard')

    # 1. Copy data from TestMethod -> TestParameter
    for param in TestParameter.objects.select_related('method').filter(method__isnull=False):
        method = param.method
        if method is None:
            continue
        param.standard_no = method.standard_no or ''
        param.standard_name = method.standard_name or ''
        param.category_id = method.category_id
        param.is_active = method.is_active
        if not param.description and method.description:
            param.description = method.description
        # Try to find Standard by standard_no
        if method.standard_no:
            std = Standard.objects.filter(
                standard_no=method.standard_no, is_deleted=False,
            ).first()
            if std:
                param.standard_id = std.pk
        param.save()

    # 2. For each TestTask with test_parameter=NULL, try to assign from test_method
    for task in TestTask.objects.filter(test_parameter__isnull=True, test_method__isnull=False):
        first_param = TestParameter.objects.filter(
            method_id=task.test_method_id, is_deleted=False,
        ).first()
        if first_param:
            task.test_parameter_id = first_param.pk
            task.save(update_fields=['test_parameter_id'])

    # 3. For each CommissionItem, try to match test_item to TestParameter.name
    CommissionItem = apps.get_model('commissions', 'CommissionItem')
    for item in CommissionItem.objects.filter(test_parameter__isnull=True, is_deleted=False):
        test_item = (item.test_item or '').strip()
        if not test_item:
            continue
        param = TestParameter.objects.filter(
            name__iexact=test_item, is_deleted=False,
        ).first()
        if param:
            item.test_parameter_id = param.pk
            item.save(update_fields=['test_parameter_id'])


def backwards(apps, schema_editor):
    pass  # no reverse


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_alter_testparameter_options_and_more'),
        ('commissions', '0005_commissionitem_test_parameter_and_more'),
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
