# Generated by Django 6.0.3 on 2026-04-01 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0004_standard_no_partial_unique'),
        ('testing', '0007_data_migrate_testmethod_to_testparameter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmethod',
            name='category',
        ),
        migrations.RemoveField(
            model_name='testmethod',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testparameter',
            name='method',
        ),
        migrations.RemoveField(
            model_name='testtask',
            name='test_method',
        ),
        migrations.AlterField(
            model_name='testtask',
            name='test_parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testparameter', verbose_name='检测参数'),
        ),
        migrations.AddConstraint(
            model_name='testparameter',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code', 'standard_no'), name='unique_param_code_per_standard'),
        ),
        migrations.DeleteModel(
            name='TestMethod',
        ),
    ]
