# Generated by Django 6.0.3 on 2026-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('commission_no', models.CharField(max_length=50, unique=True, verbose_name='委托编号')),
                ('construction_part', models.CharField(max_length=200, verbose_name='施工部位')),
                ('commission_date', models.DateField(verbose_name='委托日期')),
                ('client_unit', models.CharField(max_length=200, verbose_name='委托单位')),
                ('client_contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_witnessed', models.BooleanField(default=False, verbose_name='是否见证取样')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待评审'), ('reviewed', '已评审'), ('rejected', '已退回'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='评审日期')),
                ('review_comment', models.TextField(blank=True, verbose_name='评审意见')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '委托单',
                'verbose_name_plural': '委托单',
                'ordering': ['-commission_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('test_object', models.CharField(max_length=100, verbose_name='检测对象')),
                ('test_item', models.CharField(max_length=200, verbose_name='检测项目')),
                ('test_standard', models.CharField(blank=True, max_length=200, verbose_name='检测标准')),
                ('test_method', models.CharField(blank=True, max_length=200, verbose_name='检测方法')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('grade', models.CharField(blank=True, max_length=100, verbose_name='设计强度/等级')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit', models.CharField(default='组', max_length=20, verbose_name='单位')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '委托项目',
                'verbose_name_plural': '委托项目',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContractReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('has_capability', models.BooleanField(default=True, verbose_name='具备检测能力')),
                ('has_equipment', models.BooleanField(default=True, verbose_name='设备满足要求')),
                ('has_personnel', models.BooleanField(default=True, verbose_name='人员满足要求')),
                ('method_valid', models.BooleanField(default=True, verbose_name='方法标准有效')),
                ('sample_representative', models.BooleanField(default=True, verbose_name='样品具有代表性')),
                ('conclusion', models.CharField(choices=[('accept', '接受'), ('reject', '拒绝'), ('conditional', '有条件接受')], max_length=20, verbose_name='评审结论')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='评审日期')),
                ('comment', models.TextField(blank=True, verbose_name='评审意见')),
            ],
            options={
                'verbose_name': '合同评审',
                'verbose_name_plural': '合同评审',
            },
        ),
    ]
