# Generated by Django 6.0.3 on 2026-03-25 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='commission',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='commission',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_commissions', to=settings.AUTH_USER_MODEL, verbose_name='评审人'),
        ),
        migrations.AddField(
            model_name='commission',
            name='sub_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.subproject', verbose_name='分部分项工程'),
        ),
        migrations.AddField(
            model_name='commission',
            name='witness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.witness', verbose_name='见证人'),
        ),
        migrations.AddField(
            model_name='commissionitem',
            name='commission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commissions.commission', verbose_name='委托单'),
        ),
        migrations.AddField(
            model_name='commissionitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='contractreview',
            name='commission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_review', to='commissions.commission', verbose_name='委托单'),
        ),
        migrations.AddField(
            model_name='contractreview',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='contractreview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='评审人'),
        ),
    ]
