# Generated by Django 6.0.3 on 2026-04-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_commission_sampler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='construction_part',
            field=models.CharField(max_length=200, verbose_name='工程部位'),
        ),
    ]
