# Generated by Django 6.0.3 on 2026-04-01 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_alter_commission_construction_part'),
        ('testing', '0005_recordtemplate_test_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionitem',
            name='test_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_items', to='testing.testparameter', verbose_name='检测参数'),
        ),
        migrations.AlterField(
            model_name='commissionitem',
            name='test_item',
            field=models.CharField(blank=True, max_length=200, verbose_name='检测项目'),
        ),
        migrations.AlterField(
            model_name='commissionitem',
            name='test_object',
            field=models.CharField(blank=True, max_length=100, verbose_name='检测对象'),
        ),
    ]
