# Generated by Django 6.0.3 on 2026-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('authorized_date', models.DateField(verbose_name='授权日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '人员授权',
                'verbose_name_plural': '人员授权',
                'ordering': ['-authorized_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('cert_type', models.CharField(max_length=100, verbose_name='证书类型')),
                ('cert_no', models.CharField(max_length=100, verbose_name='证书编号')),
                ('issuing_authority', models.CharField(max_length=200, verbose_name='发证机关')),
                ('issue_date', models.DateField(verbose_name='发证日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='有效期至')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='证书附件')),
            ],
            options={
                'verbose_name': '证书',
                'verbose_name_plural': '证书',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyEval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('eval_date', models.DateField(verbose_name='评价日期')),
                ('eval_type', models.CharField(max_length=100, verbose_name='评价类型')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='评分')),
                ('conclusion', models.CharField(choices=[('competent', '胜任'), ('need_training', '需培训'), ('incompetent', '不胜任')], max_length=20, verbose_name='结论')),
                ('comment', models.TextField(blank=True, verbose_name='评价意见')),
            ],
            options={
                'verbose_name': '能力评价',
                'verbose_name_plural': '能力评价',
                'ordering': ['-eval_date'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('employee_no', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('education', models.CharField(blank=True, choices=[('high_school', '高中/中专'), ('college', '大专'), ('bachelor', '本科'), ('master', '硕士'), ('doctor', '博士')], max_length=20, verbose_name='学历')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='专业')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/staff/', verbose_name='签名样本')),
            ],
            options={
                'verbose_name': '人员档案',
                'verbose_name_plural': '人员档案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('title', models.CharField(max_length=200, verbose_name='培训内容')),
                ('training_date', models.DateField(verbose_name='培训日期')),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='培训学时')),
                ('trainer', models.CharField(blank=True, max_length=100, verbose_name='培训讲师')),
                ('assessment_result', models.CharField(choices=[('pass', '合格'), ('fail', '不合格'), ('na', '未考核')], default='na', max_length=10, verbose_name='考核结果')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='trainings/', verbose_name='培训记录附件')),
            ],
            options={
                'verbose_name': '培训记录',
                'verbose_name_plural': '培训记录',
                'ordering': ['-training_date'],
            },
        ),
    ]
