# Generated by Django 6.0.3 on 2026-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_initial'),
        ('testing', '0005_recordtemplate_test_parameters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorization',
            name='test_methods',
        ),
        migrations.AddField(
            model_name='authorization',
            name='parameters',
            field=models.ManyToManyField(blank=True, to='testing.testparameter', verbose_name='授权检测参数'),
        ),
    ]
