# Generated by Django 6.0.3 on 2026-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('certificate_no', models.CharField(max_length=100, verbose_name='证书编号')),
                ('calibration_date', models.DateField(verbose_name='检定/校准日期')),
                ('valid_until', models.DateField(verbose_name='有效期至')),
                ('calibration_org', models.CharField(max_length=200, verbose_name='校准机构')),
                ('conclusion', models.CharField(choices=[('qualified', '合格'), ('unqualified', '不合格'), ('limited', '限用')], max_length=20, verbose_name='结论')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='calibrations/', verbose_name='证书附件')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '检定/校准记录',
                'verbose_name_plural': '检定/校准记录',
                'ordering': ['-calibration_date'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('model_no', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('serial_no', models.CharField(blank=True, max_length=100, verbose_name='出厂编号')),
                ('manage_no', models.CharField(max_length=50, unique=True, verbose_name='管理编号')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='制造商')),
                ('category', models.CharField(choices=[('A', 'A类(强检)'), ('B', 'B类(非强检)'), ('C', 'C类(辅助)')], max_length=5, verbose_name='设备分类')),
                ('accuracy', models.CharField(blank=True, max_length=100, verbose_name='精度/分辨力')),
                ('measure_range', models.CharField(blank=True, max_length=200, verbose_name='量程/测量范围')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购入日期')),
                ('status', models.CharField(choices=[('in_use', '在用'), ('stopped', '停用'), ('calibrating', '送检中'), ('scrapped', '已报废')], default='in_use', max_length=20, verbose_name='状态')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='存放位置')),
                ('calibration_cycle', models.IntegerField(default=12, verbose_name='校准周期(月)')),
                ('next_calibration_date', models.DateField(blank=True, null=True, verbose_name='下次校准到期日')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '仪器设备',
                'verbose_name_plural': '仪器设备',
                'ordering': ['manage_no'],
            },
        ),
        migrations.CreateModel(
            name='EquipUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('condition_before', models.CharField(blank=True, max_length=200, verbose_name='使用前状态')),
                ('condition_after', models.CharField(blank=True, max_length=200, verbose_name='使用后状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '设备使用记录',
                'verbose_name_plural': '设备使用记录',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('maintenance_type', models.CharField(choices=[('routine', '日常保养'), ('repair', '维修'), ('overhaul', '大修')], max_length=20, verbose_name='维护类型')),
                ('maintenance_date', models.DateField(verbose_name='维护日期')),
                ('description', models.TextField(verbose_name='维护内容')),
                ('result', models.TextField(blank=True, verbose_name='维护结果')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='费用')),
            ],
            options={
                'verbose_name': '维护保养记录',
                'verbose_name_plural': '维护保养记录',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='PeriodCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('check_date', models.DateField(verbose_name='核查日期')),
                ('check_method', models.TextField(verbose_name='核查方法')),
                ('check_result', models.TextField(verbose_name='核查结果')),
                ('conclusion', models.CharField(choices=[('normal', '正常'), ('abnormal', '异常')], max_length=20, verbose_name='结论')),
            ],
            options={
                'verbose_name': '期间核查',
                'verbose_name_plural': '期间核查',
                'ordering': ['-check_date'],
            },
        ),
    ]
