# Generated by Django 6.0.3 on 2026-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('report_no', models.CharField(max_length=50, unique=True, verbose_name='报告编号')),
                ('report_type', models.CharField(blank=True, max_length=50, verbose_name='报告类型')),
                ('template_name', models.CharField(blank=True, max_length=200, verbose_name='报告模板')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_audit', '待审核'), ('pending_approve', '待批准'), ('approved', '已批准'), ('issued', '已发放'), ('archived', '已归档'), ('voided', '已作废')], default='draft', max_length=20, verbose_name='状态')),
                ('compile_date', models.DateTimeField(blank=True, null=True, verbose_name='编制日期')),
                ('audit_date', models.DateTimeField(blank=True, null=True, verbose_name='审核日期')),
                ('approve_date', models.DateTimeField(blank=True, null=True, verbose_name='批准日期')),
                ('conclusion', models.TextField(blank=True, verbose_name='检测结论')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/', verbose_name='报告PDF')),
                ('qr_code', models.CharField(blank=True, max_length=200, verbose_name='防伪二维码')),
                ('has_cma', models.BooleanField(default=True, verbose_name='CMA标识')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='发放日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '检测报告',
                'verbose_name_plural': '检测报告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('role', models.CharField(choices=[('compile', '编制'), ('audit', '审核'), ('approve', '批准')], max_length=20, verbose_name='审批角色')),
                ('action', models.CharField(choices=[('submit', '提交'), ('pass', '通过'), ('reject', '退回')], max_length=20, verbose_name='审批动作')),
                ('comment', models.TextField(blank=True, verbose_name='意见')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='电子签名')),
            ],
            options={
                'verbose_name': '报告审批记录',
                'verbose_name_plural': '报告审批记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('recipient', models.CharField(max_length=100, verbose_name='接收人')),
                ('recipient_unit', models.CharField(blank=True, max_length=200, verbose_name='接收单位')),
                ('method', models.CharField(choices=[('paper', '纸质'), ('electronic', '电子'), ('both', '纸质+电子')], max_length=20, verbose_name='发放方式')),
                ('copies', models.IntegerField(default=1, verbose_name='份数')),
                ('distribution_date', models.DateField(verbose_name='发放日期')),
                ('receiver_signature', models.CharField(blank=True, max_length=100, verbose_name='签收人')),
            ],
            options={
                'verbose_name': '报告发放记录',
                'verbose_name_plural': '报告发放记录',
                'ordering': ['-distribution_date'],
            },
        ),
    ]
