# Generated by Django 6.0.3 on 2026-03-31 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        ('testing', '0002_recordtemplate_test_parameter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='模板编号')),
                ('report_type', models.CharField(blank=True, max_length=50, verbose_name='报告类型')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('schema', models.JSONField(default=dict, verbose_name='模板定义')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('test_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to='testing.testmethod', verbose_name='关联检测方法')),
                ('test_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to='testing.testparameter', verbose_name='关联检测参数')),
            ],
            options={
                'verbose_name': '报告模板',
                'verbose_name_plural': '报告模板',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type'], name='idx_rpt_tpl_type'), models.Index(fields=['is_active'], name='idx_rpt_tpl_active')],
            },
        ),
    ]
