# Generated by Django 5.2.12 on 2026-03-31 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('old_status', models.CharField(choices=[('draft', '草稿'), ('pending_audit', '待审核'), ('pending_approve', '待批准'), ('approved', '已批准'), ('issued', '已发放'), ('archived', '已归档'), ('voided', '已作废')], max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(choices=[('draft', '草稿'), ('pending_audit', '待审核'), ('pending_approve', '待批准'), ('approved', '已批准'), ('issued', '已发放'), ('archived', '已归档'), ('voided', '已作废')], max_length=20, verbose_name='新状态')),
                ('comment', models.TextField(blank=True, verbose_name='操作备注')),
                ('operated_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='reports.report', verbose_name='报告')),
            ],
            options={
                'verbose_name': '报告状态变更日志',
                'verbose_name_plural': '报告状态变更日志',
                'ordering': ['-operated_at'],
            },
        ),
    ]
