# Generated by Django 6.0.3 on 2026-03-31 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reporttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportapproval',
            index=models.Index(fields=['report', 'role'], name='idx_rpt_appr_report_role'),
        ),
        migrations.AddIndex(
            model_name='reportapproval',
            index=models.Index(fields=['report', 'created_at'], name='idx_rpt_appr_report_created'),
        ),
    ]
