# Generated by Django 6.0.3 on 2026-04-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reportapproval_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttemplate',
            name='test_method',
        ),
    ]
