# Generated by Django 6.0.3 on 2026-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MethodValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('validation_date', models.DateField(verbose_name='验证日期')),
                ('conclusion', models.CharField(choices=[('valid', '验证通过'), ('invalid', '验证不通过')], max_length=20, verbose_name='结论')),
                ('report', models.TextField(blank=True, verbose_name='验证报告')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='validations/', verbose_name='验证附件')),
            ],
            options={
                'verbose_name': '方法验证',
                'verbose_name_plural': '方法验证',
                'ordering': ['-validation_date'],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('standard_no', models.CharField(max_length=100, unique=True, verbose_name='标准号')),
                ('name', models.CharField(max_length=300, verbose_name='标准名称')),
                ('category', models.CharField(max_length=50, verbose_name='标准分类')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('implement_date', models.DateField(blank=True, null=True, verbose_name='实施日期')),
                ('abolish_date', models.DateField(blank=True, null=True, verbose_name='废止日期')),
                ('status', models.CharField(choices=[('active', '现行'), ('upcoming', '即将实施'), ('abolished', '已废止')], default='active', max_length=20, verbose_name='状态')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='standards/', verbose_name='标准文件')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '标准',
                'verbose_name_plural': '标准',
                'ordering': ['-created_at'],
            },
        ),
    ]
