# Generated by Django 6.0.3 on 2026-03-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='replaced_case',
            field=models.CharField(blank=True, max_length=200, verbose_name='替代情况'),
        ),
    ]
