# Generated by Django 6.0.3 on 2026-03-31 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0003_standard_replaced_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='standard_no',
            field=models.CharField(max_length=100, verbose_name='标准号'),
        ),
        migrations.AddConstraint(
            model_name='standard',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('standard_no',), name='standards_standard_no_unique_if_active'),
        ),
    ]
