# Generated by Django 5.2.12 on 2026-03-31 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0004_standard_no_partial_unique'),
        ('testing', '0003_enhance_record_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='methodvalidation',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='有效期至'),
        ),
        migrations.AddField(
            model_name='methodvalidation',
            name='validation_method',
            field=models.TextField(blank=True, default='', verbose_name='验证方法'),
        ),
        migrations.AddField(
            model_name='methodvalidation',
            name='validation_no',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='验证编号'),
        ),
        migrations.AddField(
            model_name='methodvalidation',
            name='validation_results',
            field=models.JSONField(default=dict, verbose_name='验证结果数据'),
        ),
        migrations.AddField(
            model_name='methodvalidation',
            name='validation_scope',
            field=models.TextField(blank=True, default='', verbose_name='验证范围'),
        ),
        migrations.AddField(
            model_name='standard',
            name='applicable_fields',
            field=models.JSONField(blank=True, default=list, help_text='如: ["concrete", "steel"]', verbose_name='适用领域'),
        ),
        migrations.AddField(
            model_name='standard',
            name='category_legacy',
            field=models.CharField(blank=True, max_length=50, verbose_name='标准分类(旧)'),
        ),
        migrations.AddField(
            model_name='standard',
            name='key_parameters',
            field=models.JSONField(blank=True, default=list, help_text='标准涉及的主要检测参数', verbose_name='关键参数'),
        ),
        migrations.AddField(
            model_name='standard',
            name='main_content',
            field=models.TextField(blank=True, verbose_name='主要内容'),
        ),
        migrations.AddField(
            model_name='standard',
            name='scope',
            field=models.TextField(blank=True, verbose_name='适用范围'),
        ),
        migrations.AddField(
            model_name='standard',
            name='test_methods',
            field=models.ManyToManyField(blank=True, related_name='standards', to='testing.testmethod', verbose_name='关联检测方法'),
        ),
        migrations.AlterField(
            model_name='methodvalidation',
            name='conclusion',
            field=models.CharField(choices=[('valid', '验证通过'), ('invalid', '验证不通过'), ('partial', '部分通过')], max_length=20, verbose_name='结论'),
        ),
        migrations.AlterField(
            model_name='standard',
            name='status',
            field=models.CharField(choices=[('active', '现行'), ('upcoming', '即将实施'), ('abolished', '已废止'), ('draft', '草案')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='StandardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='分类编码')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('category_type', models.CharField(choices=[('national', '国家标准'), ('industry', '行业标准'), ('local', '地方标准'), ('enterprise', '企业标准'), ('international', '国际标准')], max_length=20, verbose_name='标准类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='standards.standardcategory', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '标准分类',
                'verbose_name_plural': '标准分类',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='standard',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standards', to='standards.standardcategory', verbose_name='标准分类'),
        ),
        migrations.CreateModel(
            name='StandardParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('parameter_name', models.CharField(max_length=100, verbose_name='参数名称')),
                ('parameter_code', models.CharField(blank=True, max_length=50, verbose_name='参数编码')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('requirement_type', models.CharField(choices=[('value', '数值要求'), ('range', '范围要求'), ('grade', '分级要求'), ('formula', '公式计算'), ('text', '文字描述')], max_length=20, verbose_name='要求类型')),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='最小值')),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='最大值')),
                ('target_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='目标值')),
                ('tolerance', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='允许偏差')),
                ('requirement_text', models.TextField(blank=True, verbose_name='要求描述')),
                ('test_method_clause', models.CharField(blank=True, max_length=100, verbose_name='检测方法条款')),
                ('judgment_rule', models.TextField(blank=True, verbose_name='判定规则')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='standards.standard', verbose_name='标准')),
            ],
            options={
                'verbose_name': '标准参数',
                'verbose_name_plural': '标准参数',
                'ordering': ['standard', 'parameter_code'],
            },
        ),
    ]
