# Generated by Django 6.0.3 on 2026-03-25 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('disposal_type', models.CharField(choices=[('return', '退还'), ('destroy', '销毁'), ('discard', '丢弃')], max_length=20, verbose_name='处置方式')),
                ('disposal_date', models.DateField(verbose_name='处置日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '样品处置',
                'verbose_name_plural': '样品处置',
                'ordering': ['-disposal_date'],
            },
        ),
        migrations.CreateModel(
            name='SampleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('group_no', models.CharField(max_length=50, unique=True, verbose_name='组样编号')),
                ('name', models.CharField(max_length=200, verbose_name='组样名称')),
                ('sample_count', models.IntegerField(default=3, verbose_name='组内样品数')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '样品组',
                'verbose_name_plural': '样品组',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('sample_no', models.CharField(max_length=50, unique=True, verbose_name='样品编号')),
                ('blind_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='盲样编号')),
                ('name', models.CharField(max_length=200, verbose_name='样品名称')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='规格型号')),
                ('grade', models.CharField(blank=True, max_length=100, verbose_name='设计强度/等级')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit', models.CharField(default='个', max_length=20, verbose_name='单位')),
                ('sampling_date', models.DateField(verbose_name='取样日期')),
                ('received_date', models.DateField(verbose_name='收样日期')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='生产/成型日期')),
                ('sampling_location', models.CharField(blank=True, max_length=200, verbose_name='取样地点')),
                ('status', models.CharField(choices=[('pending', '待检'), ('testing', '检测中'), ('tested', '已检'), ('retained', '留样'), ('disposed', '已处置'), ('returned', '已退还')], default='pending', max_length=20, verbose_name='状态')),
                ('retention_deadline', models.DateField(blank=True, null=True, verbose_name='留样到期日')),
                ('disposal_date', models.DateField(blank=True, null=True, verbose_name='处置日期')),
                ('disposal_method', models.CharField(blank=True, max_length=100, verbose_name='处置方式')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='commissions.commission', verbose_name='委托单')),
            ],
            options={
                'verbose_name': '样品',
                'verbose_name_plural': '样品',
                'ordering': ['-created_at'],
            },
        ),
    ]
